export const CHARACTER = {
  CHARACTER_LOAD: "CHARACTER_LOAD",
  CHARACTER_LOAD_SUCCESS: "CHARACTER_LOAD_SUCCESS",
  CHARACTER_LOAD_FAIL: "CHARACTER_LOAD_FAIL",
  CHARACTER_HAS_MORE_DATA: "CHARACTER_HAS_MORE_DATA",
};
